config-version: 1

# Set this value to false to use the old system (explicitly loading every configured challenge); set to true to use the new pool system (pick random challenge on a per-slot basis)
usePools: true

# Set this value to true to make it so that, when an active challenge expires, it gets randomized into a same one from that slot (if usePools is set to true).
rerollOnExpire: false

# These are customizable messages that appear in chat and sometimes inside of guis.
Messages:
  prefix: "&6Challenges: "
  issues:
    unknown_challenge_list: "{prefix} &cUnknown challenge &e{challenge_list}&c."
  progression:
    progression-entry: "&7{requirement-title}: &f{progression-string}"
  commands:
    opening-base-gui: "{prefix} &7Complete and claim rewards from challenges here!"
    reload: "{prefix} &2Messages and guis have been reloaded!"
    restart: "{prefix} &2This player has had their challenge history reset!"
    restartall: "{prefix} &2All players have had their challenge history reset!"
    migrate: "{prefix} &2Legacy mode data has been migrated to pool-mode based on the currently loaded challenge data!"
  requirements:
    # When listing a player's progress on a challenge, these will be the prefix for that
    progression-shorthand:
      catch_pokemon: "{pokename} Captured"
      evolve_pokemon: "{pokename} Evolved"
      defeat_battler: "{battlerData} Defeated"
      harvest_apricorn: "Apricorns Harvested"
      harvest_berry: "Berries Harvested"
      mine_block: "{blockData} Blocks Mined"
      place_block: "{blockData} Blocks Placed"
      complete_challenge: "Challenges Completed"
      pokemon_scanned: "Pokémon Scanned"
      pokemon_seen: "Pokémon Seen"
      milestone_time_played: "Seconds Passed"
      use_rare_candy: "Rare Candies Used"
      hatch_egg: "Eggs Hatched"
      exp_gained: "EXP Gained"
      level_up_once: "Levels Gained"
      level_up_to: "Pokémon Leveled"
      trades_completed: "Trades"
      fossils_revived: "Fossils Revived"
      login: "Login"
  challenges:
    progression-string: "&f{current}&7/{target}"
    completed:
      - "&6Challenges: &bChallenge Completed: {challenge}"
    offcooldown:
      - "&6Challenges: &bChallenge Refreshed: {challenge}"
    expired:
      - "&6Challenges: &bChallenge Expired: {challenge}"
    randomized:
      - "&6Challenges: &bChallenge Available: {challenge}"
    progression_status:
      before-attempt: "&6Status: &ePending (Click to track)"
      during-attempt: "&6Status: &aIn progress"
      post-completion: "&6Status: &2Completed"
    failure:
      time-ran-out: "{prefix} &cChallenge: &6{challenge} &cfailed!"
    tracking-tag:
      before-starting:
        - "&eChallenge time: &7{time-remaining}"
      after-starting:
        - "&eTime remaining: &7{time-remaining}"
      cooldown:
        - "&eAvailable again in: {time-remaining}"

# This is the menu where each challenge list is displayed.
# Here you can move the lists and add new ones.
base-menu:
  window-name: "&6Challenges"
  structure:
    - "# # # # # # # # #"
    - "# 1 2 3 - # 4 - #"
    - "# # # # # # # # #"
    - "# - - - - - - - #"
    - "# # # # # # # # #"
  ingredients:
    '#':
      material: BLACK_STAINED_GLASS_PANE
      name: " "
    '1':
      linked_to: "daily" # Which gui it is referencing.
      material: BOOK
      name: "&6Daily Challenges"
      lore:
        - "&7Click me to see a list of Daily Challenges"
    '2':
      linked_to: "weekly" # Which gui it is referencing.
      material: BOOK
      name: "&6Weekly Challenges"
      lore:
        - "&7Click me to see a list of Weekly Challenges"
    '3':
      linked_to: "monthly" # Which gui it is referencing.
      material: BOOK
      name: "&6Monthly Challenges"
      lore:
        - "&7Click me to see a list of Monthly Challenges"
    '4':
      linked_to: "seasonal" # Which gui it is referencing.
      material: ENCHANTED_BOOK
      enchanted-effect: true
      hiddenTooltips: ALL
      name: "&Seasonal Challenges"
      lore:
        - "&7Click me to see a list of Seasonal Challenges"

# This is what the challenge items should default to after being started or completed.
# Only the material will change currently, so their custom lore and name will persist.
challenges:
  active-challenge-item: # Will only replace material of the challenge, not title or lore.
    material: COMPASS
  completed-challenge-item: # Will only replace material of the challenge, not title or lore.
    material: END_CRYSTAL